CMake: Link libm to test binaries if available
xiph/vorbis pull request #82
Opened 2021-05-09 11:34 UTC by diizzyy

If libm is available link it to test binaries which will otherwise fail to compile
Tested on FreeBSD 13-STABLE

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

2021-05-09 11:36 UTC, diizzyy commented
@evpobr

2021-05-09 13:10 UTC, evpobr requested changes
Windows builds are failing - `M_PI` undefined.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-160

2021-05-09 16:27 UTC, diizzyy commented
Not related? This issue occured before my PR

https://github.com/xiph/vorbis/commit/83a82dd9296400d811b78c06e9ca429e24dd1e5c --> https://ci.appveyor.com/project/rillian/vorbis/builds/36177388 --> https://ci.appveyor.com/project/rillian/vorbis/builds/36177388/job/t06shr5lh00ejakb

2021-05-09 16:50 UTC, evpobr commented
Can you add that define for MSVC to check it?

2021-05-09 16:51 UTC, rillian commented
IIRC this is correct. `lib/os.h` has a fallback definition of `M_PI` which allows the main library to compile, but `test/util.c` doesn't include it.

We could address the issue by
- copying the fallback `#define` to `util.c`.
- including `os.h` in `util.c`.
- Passing `_USE_MATH_DEFINES` in from the build system.

I'm not sure what the best approach is here. Happy to see a proposal.

2021-05-09 16:52 UTC, diizzyy commented
I have no idea idea to fix it for MSVC and additionally no test box so unfortunately not.

2021-05-09 16:54 UTC, evpobr commented
I guess it is already done in #77 and still not merged.

Probably you need to make pull request to <https://gitlab.xiph.org/xiph/vorbis>.

2021-05-10 05:16 UTC, rillian commented
We've addressed the `M_PI` issue. Could you please rebase to confirm appveyor failure goes away?

2021-05-10 10:04 UTC, diizzyy commented
Compiles fine now, thanks! :-)

2021-05-12 07:59 UTC, diizzyy commented
@rillian 
Anything else you want me to do?

2021-05-12 17:05 UTC, rillian commented
Nope. Merged upstream in 84c023699cdf023a32fa4ded32019f194afcdad0. Thanks for the patch!

2021-05-12 17:05 UTC, closed without merging